[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Configura a velocidade do Monitor Serial
monitor_speed = 115200

; Baixa as bibliotecas do MLX90614 e do DHT22 automaticamente
lib_deps = 
	adafruit/Adafruit MLX90614 Library @ ^2.1.5
	adafruit/DHT sensor library @ ^1.4.6
	adafruit/Adafruit Unified Sensor @ ^1.1.14